const { BY_KEY } = require('../dataroom/template');

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const IMPORTANCE_COLORS = {
  critical: '#b42318',
  important: '#b54708',
  nice_to_have: '#475467'
};

// Renders the analysis (and optional build result) as a self-contained HTML
// report, used both for the in-app preview and the emailed report.
function renderReportHtml(analysis, build) {
  const a = analysis;
  const rootLink = build && build.rootFolder ? build.rootFolder.webViewLink : null;

  const categoryRows = a.categories
    .map(
      (c) => `
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #eaecf0;">${esc(c.folder.replace(/_/g, ' '))}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #eaecf0;text-align:right;font-variant-numeric:tabular-nums;">
            ${c.fileCount > 0 ? c.fileCount : '<span style="color:#b42318;">0</span>'}
          </td>
        </tr>`
    )
    .join('');

  const gapRows = a.gaps
    .map((g) => {
      const cat = BY_KEY[g.category] ? BY_KEY[g.category].title : g.category;
      const color = IMPORTANCE_COLORS[g.importance] || '#475467';
      return `
        <li style="margin-bottom:14px;">
          <span style="display:inline-block;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:#fff;background:${color};padding:2px 8px;border-radius:10px;">
            ${esc(g.importance.replace('_', ' '))}
          </span>
          <strong style="margin-left:6px;">${esc(cat)}:</strong> ${esc(g.item)}
          <div style="color:#475467;margin-top:3px;">${esc(g.whatToProvide)}</div>
        </li>`;
    })
    .join('');

  return `
  <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;max-width:680px;margin:0 auto;color:#101828;">
    <h1 style="font-size:22px;margin:0 0 4px;">${esc(a.companyName)} — Data Room Report</h1>
    <p style="color:#667085;margin:0 0 20px;">Generated ${esc(new Date(a.generatedAt).toLocaleString())}</p>

    ${
      a.summary
        ? `<div style="background:#f9fafb;border:1px solid #eaecf0;border-radius:10px;padding:16px 18px;margin-bottom:20px;">
            <div style="font-weight:700;margin-bottom:6px;">Executive Summary</div>
            <div style="color:#344054;">${esc(a.summary)}</div>
          </div>`
        : ''
    }

    <div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px;">
      ${statCard(a.stats.placedFiles + ' / ' + a.stats.totalFiles, 'files organized')}
      ${statCard(a.stats.categoriesWithContent + ' / ' + a.stats.totalCategories, 'sections with content')}
      ${statCard(String(a.stats.criticalGaps), 'critical gaps')}
    </div>

    ${
      rootLink
        ? `<p style="margin:0 0 24px;"><a href="${esc(rootLink)}" style="background:#0e7490;color:#fff;text-decoration:none;padding:10px 16px;border-radius:8px;font-weight:600;display:inline-block;">Open the data room in Google Drive →</a></p>`
        : `<p style="margin:0 0 24px;color:#b54708;background:#fffaeb;border:1px solid #fedf89;border-radius:8px;padding:10px 14px;">Preview only — the data room was not built in Drive (dry run).</p>`
    }

    <h2 style="font-size:16px;margin:0 0 8px;">Structure & Coverage</h2>
    <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px;">
      <thead>
        <tr>
          <th style="text-align:left;padding:8px 12px;border-bottom:2px solid #d0d5dd;color:#667085;font-weight:600;">Section</th>
          <th style="text-align:right;padding:8px 12px;border-bottom:2px solid #d0d5dd;color:#667085;font-weight:600;">Files</th>
        </tr>
      </thead>
      <tbody>${categoryRows}</tbody>
    </table>

    <h2 style="font-size:16px;margin:0 0 12px;">Information We Need to Complete It</h2>
    ${
      a.gaps.length
        ? `<ul style="list-style:none;padding:0;margin:0;font-size:14px;">${gapRows}</ul>`
        : `<p style="color:#067647;">No gaps detected — the data room looks complete. 🎉</p>`
    }

    ${
      build && build.errors && build.errors.length
        ? `<h2 style="font-size:16px;margin:24px 0 8px;color:#b42318;">Items that could not be copied</h2>
           <ul style="font-size:13px;color:#667085;">${build.errors
             .map((e) => `<li>${esc(e.file)} — ${esc(e.error)}</li>`)
             .join('')}</ul>`
        : ''
    }

    <p style="color:#98a2b3;font-size:12px;margin-top:32px;border-top:1px solid #eaecf0;padding-top:12px;">
      Generated by Data Room Builder. Originals were copied, never moved or modified.
    </p>
  </div>`;
}

function statCard(big, label) {
  return `
    <div style="flex:1;min-width:140px;background:#fff;border:1px solid #eaecf0;border-radius:10px;padding:14px 16px;">
      <div style="font-size:22px;font-weight:700;">${esc(big)}</div>
      <div style="color:#667085;font-size:13px;">${esc(label)}</div>
    </div>`;
}

module.exports = { renderReportHtml };
